apiVersion: v1
kind: Service
metadata:
  name: mongo-kafka-service
spec:
  selector:
    app: mongo-kafka-pod
  ports:
  - name: mongodb
    protocol: TCP
    port: 27017
    targetPort: 27017
  - name: kafka
    protocol: TCP
    port: 9092
    targetPort: 9092
  - name: zookeeper
    protocol: TCP
    port: 2181
    targetPort: 2181
  type: NodePort    # Or LoadBalancer, ClusterIP    
