services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports:
      - "5000:5000"
      - "7000:7000"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
    command: /home/node/app/node_modules/.bin/nodemon app.js 
    depends_on:
      - db
      - zookeeper
  db:
    image: mongo:4.1.8-xenial
    container_name: db
    restart: unless-stopped
    volumes:     
      - dbdata:/data/db
    networks:
      - app-network  
  zookeeper:
    image: zookeeper:3.8.1
    ports:
      - "2181:2181"
  kafka:
    image: confluentinc/kafka:7.4.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:        